version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ultimate_auth
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: